/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.ehs.service;
import cn.zhuatech.ehs.common.BusinessException; import cn.zhuatech.ehs.dto.EhsDto.*; import cn.zhuatech.ehs.model.*; import cn.zhuatech.ehs.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class EhsService {
    private final SafetyInspectionRepository orders; private final CorrectiveActionRecordRepository reports; private final HazardControlRepository hazardControl; private final IncidentReportRepository incidentReports; private final CurrentUserService current;
    public EhsService(SafetyInspectionRepository orders,CorrectiveActionRecordRepository reports,HazardControlRepository hazardControl,IncidentReportRepository incidentReports,CurrentUserService current){this.orders=orders;this.reports=reports;this.hazardControl=hazardControl;this.incidentReports=incidentReports;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getSafetyAreaCode();List<SafetyInspection> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findBySafetyAreaCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<SafetyInspectionView> safetyInspections(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){SafetyInspection order=orders.findById(id).orElseThrow(()->new BusinessException("安全巡检不存在"));if(order.getStatus()==SafetyInspection.Status.COMPLETED)throw new BusinessException("已完成任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成数量不能超过任务剩余数量");order.report(request.goodQty(),request.defectQty());reports.save(new CorrectiveActionRecord(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<SafetyInspection> list){int planned=list.stream().mapToInt(SafetyInspection::getPlannedQty).sum(),done=list.stream().mapToInt(SafetyInspection::getCompletedQty).sum(),defects=list.stream().mapToInt(SafetyInspection::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("今日巡检",String.format("%,d",planned),list.size()+" 张安全巡检","blue"),new Metric("巡检完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("结果安全率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项异常","warn"),new Metric("风险控制异常",hazardControl.countByStatus(HazardControl.Status.ALARM)+"",incidentReports.countByResult(IncidentReport.Result.PENDING)+" 项待复核","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),hazardControl.findAllByOrderByCodeAsc().stream().map(e->new ControlView(e.getCode(),e.getName(),e.getSafetyArea().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),incidentReports.findTop10ByOrderByIdDesc().stream().map(i->new IncidentReportView(i.getIncidentReportNo(),i.getSafetyInspection().getOrderNo(),i.getSafetyInspection().getProductName(),i.getIncidentReportType(),i.getIncidentReportQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private SafetyInspectionView view(SafetyInspection o){return new SafetyInspectionView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getSafetyArea().getName(),o.getSafetyArea().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(SafetyInspection o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
